import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FloatingChatButton, ChatWindow } from "@/modules/chatbot";
import { FloatingAddNoteButton } from "@/shared/components/ui/FloatingAddNoteButton";
import { GlobalNotesPanel } from "@/modules/notes/components/GlobalNotesPanel";
import { ClientOnly } from "@/shared/components/common/ClientOnly";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen overflow-hidden">
          {/* Main content area */}
          <div className="flex-1 overflow-hidden">
            {children}
          </div>
          
          {/* Right side notes panel */}
          <ClientOnly>
            <GlobalNotesPanel />
          </ClientOnly>
        </div>
        
        <ChatWindow />
        <FloatingChatButton />
        <ClientOnly>
          <FloatingAddNoteButton />
        </ClientOnly>
      </body>
    </html>
  );
}
